[build]
  publish = "public"
  command = "echo 'No build command needed'"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "/login/google"
  to = "/.netlify/functions/server"
  status = 200
  force = true

[[redirects]]
  from = "/is_authenticated"
  to = "/.netlify/functions/server"
  status = 200
  force = true

[[redirects]]
  from = "/logout"
  to = "/.netlify/functions/server"
  status = 200
  force = true

[[headers]]
  for = "/static/script.js"
  [headers.values]
  Content-Type = "application/javascript"
