[build]
  publish = "public"  # Keep this if your frontend files are in /public
  command = "echo 'No build command needed'"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server"
  status = 200

[[headers]]
  for = "/static/script.js"  # ✅ Update path to reflect new location
  [headers.values]
  Content-Type = "application/javascript"
